// @flow Created by 陈其丰 on 2018/11/22.

// 更新时间
export const UPDATE_TIME_REQUEST = 'FETCH/COMPONENT/WORD_ITEM/UPDATE_TIME_REQUEST';
export const UPDATE_TIME_SUCCESS = 'FETCH/COMPONENT/WORD_ITEM/UPDATE_TIME_SUCCESS';
export const UPDATE_TIME_FAILURE = 'FETCH/COMPONENT/WORD_ITEM/UPDATE_TIME_FAILURE';

// 更新级别
export const UPDATE_LEVEL_REQUEST = 'FETCH/COMPONENT/WORD_ITEM/UPDATE_LEVEL_REQUEST';
export const UPDATE_LEVEL_FAILURE = 'FETCH/COMPONENT/WORD_ITEM/UPDATE_LEVEL_FAILURE';
export const UPDATE_LEVEL_SUCCESS = 'FETCH/COMPONENT/WORD_ITEM/UPDATE_LEVEL_SUCCESS';

// 删除
export const DELETE_ITEM_REQUEST = 'FETCH/COMPONENT/WORD_ITEM/DELETE_ITEM_REQUEST';
export const DELETE_ITEM_FAILURE = 'FETCH/COMPONENT/WORD_ITEM/DELETE_ITEM_FAILURE';
export const DELETE_ITEM_SUCCESS = 'FETCH/COMPONENT/WORD_ITEM/DELETE_ITEM_SUCCESS';