// @flow Created by 陈其丰 on 2018/11/15.


/*单词检索*/
export const FETCH_SEARCH_ITEM_REQUEST = 'INDEX/STUDY/FETCH/SEARCH_ITEM_REQUEST';
export const FETCH_SEARCH_ITEM_SUCCESS = 'INDEX/STUDY/FETCH/SEARCH_ITEM_SUCCESS';
export const FETCH_SEARCH_ITEM_FAILURE = 'INDEX/STUDY/FETCH/SEARCH_ITEM_FAILURE';

