// @flow Created by 陈其丰 on 2018/11/15.


/*今日单词*/
export const FETCH_QUERY_LIST_REQUEST = 'INDEX/STUDY/FETCH/QUERY_TODAY_WORD_LIST_REQUEST';
export const FETCH_QUERY_LIST_SUCCESS = 'INDEX/STUDY/FETCH/QUERY_TODAY_WORD_LIST_SUCCESS';
export const FETCH_QUERY_LIST_FAILURE = 'INDEX/STUDY/FETCH/QUERY_TODAY_WORD_LIST_FAILURE';



export const INSERT_ITEM = 'INDEX/STUDY/TODAY_WORD/INSERT_ITEM';
