// @flow Created by 陈其丰 on 2018/11/15.


/*今日单词*/
export const QUERY_LIST = 'INDEX/STUDY/TODAY_WORD/QUERY_LIST';
export const DELETE_ITEM = 'INDEX/STUDY/TODAY_WORD/DELETE_ITEM';
export const UPDATE_ITEM = 'INDEX/STUDY/TODAY_WORD/UPDATE_ITEM';
export const INSERT_ITEM = 'INDEX/STUDY/TODAY_WORD/INSERT_ITEM';
