// @flow Created by 陈其丰 on 2018/11/26.

export const FETCH_WORD_LIST_REQUEST = 'MINE/WORD/FETCH/WORD_LIST_REQUEST';
export const FETCH_WORD_LIST_SUCCESS = 'MINE/WORD/FETCH/WORD_LIST_SUCCESS';
export const FETCH_WORD_LIST_FAILURE = 'MINE/WORD/FETCH/WORD_LIST_FAILURE';


export const EMPTY_WORD_LIST = 'MINE/WORD/EMPTY_WORD_LIST';