// @flow Created by 陈其丰 on 2018/11/26.

export const UPDATE_ALL_COUNT = 'INDEX/MINE/UPDATE_ALL_COUNT';
export const FETCH_ALL_COUNT_REQUEST = 'INDEX/MINE/FETCH/ALL_COUNT_REQUEST';
export const FETCH_ALL_COUNT_SUCCESS = 'INDEX/MINE/FETCH/ALL_COUNT_SUCCESS';
export const FETCH_ALL_COUNT_FAILURE = 'INDEX/MINE/FETCH/ALL_COUNT_FAILURE';


export const UPDATE_HARD_COUNT = 'INDEX/MINE/UPDATE_HARD_COUNT';
export const FETCH_HARD_COUNT_REQUEST = 'INDEX/MINE/FETCH/HARD_COUNT_REQUEST';
export const FETCH_HARD_COUNT_SUCCESS = 'INDEX/MINE/FETCH/HARD_COUNT_SUCCESS';
export const FETCH_HARD_COUNT_FAILURE = 'INDEX/MINE/FETCH/HARD_COUNT_FAILURE';