// @flow Created by 陈其丰 on 2018/11/14.

/*
* 单词列表
*/
// export const FETCH_WORD_LIST_REQUEST = 'INDEX/EXAM/FETCH/WORD_LIST_REQUEST';
// export const FETCH_WORD_LIST_SUCCESS = 'INDEX/EXAM/FETCH/WORD_LIST_SUCCESS';
// export const FETCH_WORD_LIST_FAILURE = 'INDEX/EXAM/FETCH/WORD_LIST_FAILURE';
//更新单词列表
export const UPDATE_WORD_LIST = 'INDEX/EXAM/UPDATE_WORD_LIST';


//更新单个单词
export const UPDATE_WORD_ITEM = 'INDEX/EXAM/UPDATE_WORD_ITEM';

//删除单个单词
export const DELETE_WORD_ITEM = 'INDEX/EXAM/DELETE_WORD_ITEM';

