// @flow Created by 陈其丰 on 2018/11/14.

/*
* 单词列表
*/

export const FETCH_WORD_LIST_REQUEST = 'INDEX/EXAM/FETCH/WORD_LIST_REQUEST';
export const FETCH_WORD_LIST_SUCCESS = 'INDEX/EXAM/FETCH/WORD_LIST_SUCCESS';
export const FETCH_WORD_LIST_FAILURE = 'INDEX/EXAM/FETCH/WORD_LIST_FAILURE';


